---
sudo: true
dist: xenial
language: python
python:
    - "3.6"

addons:
    apt:
        packages:
            - build-essential
            - python-dev

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted';
    - sudo apt-get -y update;
    - sudo apt-get install -y python-krbv yum
    - wget http://archive.ubuntu.com/ubuntu/pool/universe/k/koji/koji-common_1.10.0-1_all.deb
    - wget http://archive.ubuntu.com/ubuntu/pool/universe/k/koji/koji-client_1.10.0-1_all.deb
    - sudo dpkg -i koji-common_1.10.0-1_all.deb
    - sudo dpkg -i koji-client_1.10.0-1_all.deb

install:
    - pip install -r requirements/ci.txt

before_script:
    - sudo /etc/init.d/postgresql stop
    - sudo apt-get -y remove --purge postgresql-9.1
    - sudo apt-get -y remove --purge postgresql-9.2
    - sudo apt-get -y remove --purge postgresql-9.3
    - sudo apt-get -y remove --purge postgresql-9.4
    - sudo apt-get -y autoremove
    - travis_retry sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
    - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
    - sudo apt-get update
    - sudo apt-get -y install postgresql-9.5
    - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
    - sudo sh -c 'echo "local all all trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
    - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
    - sudo service postgresql restart 9.5

script: "make lint test"
